name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Windows-latest:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Make compiler
        run: |
          mingw32-make
          mingw32-make check

  Ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make compiler
      run: | 
        make
        make check