name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: GCC Compile Compiler
      run: |
        make clean
        make
        make check

    - name: Install MinGW
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64

    - name: MinGW Compile Compiler
      run: |
        make gccCompiler=x86_64-w64-mingw32-gcc clean
        make gccCompiler=x86_64-w64-mingw32-gcc
        make gccCompiler=x86_64-w64-mingw32-gcc check

    - name: Unit Test
      run: |
        make munit
        ./munit

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Pytest
      run: |
        python tests/test_behavior.py